apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: roboshop
type: Opaque
data:
  AMQP_USER: cm9ib3Nob3A=
  AMPQ_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    app: payment
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        app: payment
        project: roboshop
        tier: app
    spec:
      containers:
        - name: payment
          image: satishkalari/payment:v1
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: payment-secret
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  type: ClusterIP
  selector:
    app: payment
    project: roboshop
    tier: app
  ports:
    - name: payment
      protocol: TCP
      port: 8080 # Service port
      targetPort: 8080 # Container port
---