apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
  namespace: roboshop
  labels:
    app: shipping
    project: roboshop
    tier: app
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels: # Labels are used to select the Pods and Services
    app: shipping
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: # Select the Pods based on labels to manage the Pods
      app: shipping
      project: roboshop
      tier: app
  template:
    metadata:
      labels: # The labels in Pod template
        app: shipping
        project: roboshop
        tier: app
    spec:
      containers:
        - name: shipping
          image: "satishkalari/shipping:v1"
          envFrom:
            - configMapRef:
                name: shipping-config
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    app: shipping
    project: roboshop
    tier: app
spec:
  type: ClusterIP
  selector:
    app: shipping
    project: roboshop
    tier: app
  ports:
    - name: shipping
      protocol: TCP
      port: 8080
      targetPort: 8080
