apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
  namespace: roboshop
data:
  MONGO: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    app: catalogue
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        app: catalogue
        project: roboshop
        tier: app
    spec:
      containers:
        - name: catalogue
          image: satishkalari/catalogue:v1
          imagePullPolicy: Always
          envfrom:
            - configMapRef:
                name: catalogue-config
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  type: ClusterIP
  selector:
    app: catalogue
    project: roboshop
    tier: app
  ports:
    - name: catalogue
      protocol: TCP
      port: 8080 # Service port
      targetPort: 8080 # Container port