apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: roboshop
data:
  MONGO: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    app: user
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        app: user
        project: roboshop
        tier: app
    spec:
      containers:
        - name: user
          image: satishkalari/user:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: user-config
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  type: ClusterIP
  selector:
    app: user
    project: roboshop
    tier: app
  ports:
    - name: user
      protocol: TCP
      port: 8080 # Service port
      targetPort: 8080 # Container port